name: intern_task
channels:
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - comtypes=1.1.7
  - cryptography=2.9.2
  - et_xmlfile=1.0.1
  - icc_rt=2019.0.0
  - idna=2.10
  - intel-openmp=2020.1
  - jdcal=1.4.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openpyxl=3.0.4
  - openssl=1.1.1g
  - pandas=1.0.5
  - pip=20.1.1
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pywin32=227
  - requests=2.24.0
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.3
  - urllib3=1.25.9
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xlwings=0.19.5
  - zlib=1.2.11

